FROM node:14 as build

WORKDIR /app/frontend

COPY . /app/frontend

ENV PATH /app/frontend/node_modules/.bin:$PATH

RUN yarn

RUN yarn build

# Production environment
FROM nginx:alpine

COPY --from=build /app/frontend/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
