# Generated by Django 3.1.2 on 2020-11-24 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('courses', '0001_initial'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('training_session', models.TextField(choices=[('2019-2020', 'Session 1920'), ('2020-2021', 'Session 2021'), ('2021-2022', 'Session 2122'), ('2022-2023', 'Session 2223'), ('2023-2024', 'Session 2324')])),
                ('event_type', models.TextField(choices=[('Exam', 'Exam'), ('Discovery Learning', 'Discovery Learning'), ('Lecture', 'Lecture'), ('Whole Class', 'Whole Class'), ('Special Events', 'Special Events'), ('Self Directed Learning', 'Self Directed Learning'), ('Labs', 'Labs'), ('Team Based Learning', 'Team Based Learning'), ('Small Group', 'Small Group'), ('Career Planning', 'Career Planning'), ('Learning Communities', 'Learning Communities'), ('Clinical Skills', 'Clinical Skills'), ('Clinical Shadowing', 'Clinical Shadowing'), ('OSCE', 'Osce')])),
                ('event_title', models.TextField()),
                ('event_desc', models.TextField(null=True)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_duration', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('course_id', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            options={
                'db_table': 'cal_event',
            },
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('event_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField(max_length=120, null=True)),
                ('vodcast_url', models.TextField(max_length=120, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
            ],
            options={
                'db_table': 'cal_event_group',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(max_length=120)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cal_tag',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('event_tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('tag_id', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='events.tag')),
            ],
            options={
                'db_table': 'cal_event_tag',
            },
        ),
        migrations.CreateModel(
            name='EventGroupInstructor',
            fields=[
                ('event_group_instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('event_group_id', models.ForeignKey(db_column='event_group_id', on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('instructor_id', models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='participants.participant')),
            ],
            options={
                'db_table': 'cal_event_group_instructor',
            },
        ),
    ]
